### ISSUE TITLE
Update KuberSphere Docs needed

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/devops-agent#1]
The following repo will be deleted:

- https://github.com/kubesphere/builder-base
- https://github.com/kubesphere/builder-maven
- https://github.com/kubesphere/builder-nodej
- https://github.com/kubesphere/builder-go

They are replaced by https://github.com/kubesphere/devops-agent . So, https://github.com/kubesphere/docs.kubesphere.io needs to be updated for https://kubesphere.io/docs.

**Comment by LinuxSuRen** [comment]
I didn't find any reference for `https://github.com/kubesphere/builder-base`

see also https://github.com/kubesphere/docs.kubesphere.io/search?q=kubesphere%2Fbuilder-base

**Comment by shaowenchen** [comment]
It looks ok. 

/close
