### ISSUE TITLE
Discussion: There is no need to maintain so many docker images

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/devops-agent#26]
There is no need to maintain so many docker images for dedicated requirements. The main shortage of devops-agent we provided is that we can't change tools' version conveniently in Jenkinsfile, and to do that we have to build another docker image for dedicated tool version. The world has too many tools we don't want to build them twice.

However, maybe we can change our mind, we could provide another way that users could config and apply their pod templates easily. If do that, we'll be free.

**Comment by JohnNiang** [comment]
There is also an example about custom pod template:

```groovy
pipeline {
  agent {
    kubernetes {
      //cloud 'kubernetes'
      label 'node:fermium'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nodejs
    image: node:fermium
    command: ['cat']
    tty: true
"""
    }
  }
  stages {
    stage('Run nodejs') {
      steps {
        container('nodejs') {
          sh '''
          node -v
          npm -v
          yarn -v
          '''
        }
      }
    }
  }
}
```

If we could put the custom pod template into global pod template easily, it would be very nice.

**Comment by LinuxSuRen** [comment]
I don't know what do you want to propose here. Please give a clear to-do list instead of just an idea. And the pros and cons for each item are necessary.

By the way, where does the image come from if you propose to use a custom pod template?

**Comment by Dishone** [comment]
@LinuxSuRen Hi Rick, when I was building my flutter image proxy last night. I thought of a design. We can allow users to customize the image they need by providing a web interface. Similar to s2ibuilders. This is just an initial idea, I think I can help.

**Comment by LinuxSuRen** [comment]
see also https://github.com/kubesphere/devops-agent/issues/75
/close
