### ISSUE TITLE
Yum resources not cleaned up manually after Podman installation in base/podman/Dockerfile

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/devops-agent#62]
Please see the Podman installation:
https://github.com/kubesphere/devops-agent/blob/45621490aa967122acaba25da6ef6c603ce75f5c/base/podman/Dockerfile#L60-L62

After the installation, yum resources were not cleaned up.

/kind enhancement

**Comment by JohnNiang** [comment]
I could confirm that the size of the last docker image will be decreased, please see the screenshot below:

![image](https://user-images.githubusercontent.com/16865714/144692308-d88a8dfc-8680-43c0-9649-22fd39963057.png)

**Comment by JohnNiang** [comment]
Dive into docker image:

- kubespheredev/builder-base:v3.2.0-podman

![image](https://user-images.githubusercontent.com/16865714/144692868-612b0749-2e02-4640-b6ac-c91c5311ef19.png)

- kubespheredev/builder-base:dev-v3.2.0-podman (After cleaning up)

![image](https://user-images.githubusercontent.com/16865714/144692829-b05ae9c8-6c93-4077-9971-95a9c46420ac.png)

**Comment by JohnNiang** [comment]
I suggest putting Podman installation into 
https://github.com/kubesphere/devops-agent/blob/45621490aa967122acaba25da6ef6c603ce75f5c/base/podman/Dockerfile#L4

to reduce layer generation and total size of the docker image.

/kind optimization
/good-first-issue

**Comment by LinuxSuRen** [comment]
hi @JohnNiang , thanks for reporting this issue. But IMO this might not be a high-priority issue. Especially you already putted a `good-first-issue` label for it.
