### ISSUE TITLE
docker.io/kubesphere/builder-gradle does not have any tags

### ISSUE THREAD

**Issue by Aurorxa** [kubesphere/devops-agent#72]

**Comment by LinuxSuRen** [comment]
hi @Aurorxa thanks for your reporting. But we didn't publish it. That means we don't support it officially.

**Comment by Aurorxa** [comment]
Can Devops customize the packer，eg maven 、go ，because the current Maven packer is 1.8, maybe we need 11 。

**Comment by LinuxSuRen** [comment]
> Can Devops customize the packer，eg maven 、go ，because the current Maven packer is 1.8, maybe we need 11 。

Of course, you just need to change the existing Dockerfile, then build it by yourself.

For example, change the maven version from https://github.com/kubesphere/devops-agent/blob/d7797562cce10d844ab146fc8c6be39024d94f18/maven/Dockerfile#L11

**Comment by Aurorxa** [comment]
t present, Java uses Gradle build tools a lot, hope to add Gradle.

**Comment by Aurorxa** [comment]
At present, Java uses Gradle build tools a lot, hope to add Gradle.

**Comment by LinuxSuRen** [comment]
see also https://github.com/kubesphere/devops-agent/issues/75
/close
